resolver: lts-13.26

packages:
- lib/kreb-control/
- lib/kreb-format/
- lib/kreb-unit/
- lib/kreb-prop/
- lib/kreb-category/
- lib/kreb-optics/
- lib/kreb-reflect/
- lib/kreb-arith/
- lib/kreb-effect/
- lib/kreb-struct/
- lib/kreb-text/
- lib/kreb-lang/
- lib/kreb-editor-core/
- lib/kreb-editor-tui/
- lib/kreb-editor/
- lib/kreb-pandoc/

extra-deps:
- Hclip-3.0.0.4@sha256:df341c936594465df25c3b9f93f6ebe3110a36d64a51dbbd1dbd557394bbdba4,1648
